# Generated by Django 4.2.16 on 2024-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('short_url', models.URLField(blank=True, null=True)),
                ('retention', models.CharField(choices=[('1 Week', '1 Week'), ('Permanent', 'Permanent')], max_length=20)),
            ],
        ),
    ]
